### ISSUE TITLE
TypeScript Error: This expression is not callable

### ISSUE THREAD

**Issue by nickfla1** [MathiasGilson/Tailwind-Styled-Component#1]
I'm getting the following TypeScript error when I use this package in a .tsx file.
`TS2349: This expression is not callable. Not all constituents of type 'FunctionTemplate | undefined' are callable. Type 'undefined' has no call signatures.`

- _tsc_ version: `4.0.5`
- _tailwind-styled-components_ version: `1.0.6`

TypeScript configuration:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "./node_modules",
    "**/**/*.svg"
  ]
}
```

**Comment by MathiasGilson** [comment]
Hello, thank you for your report,

can you send me the code you are using when you import and call tailwind-styled-components ?

Many thanks

**Comment by padunk** [comment]
Hi,
I also get this error.
I create a project with create-react-app `--template typescript`

```
import tw from 'tailwind-styled-components'

const Container = tw.div`
  flex
  items-center
  justify-center
`

const Layout = ({children}) => {
  return <Container>{children}</Container>
}
```

![Screenshot 2021-01-04 14 12 34](https://user-images.githubusercontent.com/25411350/103510110-2011d580-4e97-11eb-984c-b8d86236c5a0.png)

**Comment by nickfla1** [comment]
Hello, @MathiasGilson
I was using the example code I found in the README.

**Comment by MathiasGilson** [comment]
Setting `"strict": false` in `tsconfig.json` removed the error.
I know this is not a solution, I'll try to make the package strictly type.
Stay tuned!

**Comment by MathiasGilson** [comment]
Just push the version `1.0.7` that should solve this issue.

Many thanks for your detailed reports
