### ISSUE TITLE
Input onChange and onFocus props are not working

### ISSUE THREAD

**Issue by MathiasGilson** [MathiasGilson/Tailwind-Styled-Component#10]
The props don't seems to be correctly propagated to the React Element.

```tsx
<Input onChange={console.log} onFocus={() => console.log(`focus`)} />

const Input = tw.input``
```

Check the example directory for a reproducible example

**Comment by MathiasGilson** [comment]
@m50 any ideas ?

**Comment by m50** [comment]
I'll take a look later today, if/when I have time.

My fiancé just arrived back in town after being away for a year, so no guarantees.

Pretty sure I didn't change the forwarded prop types at all... But I'll take a look

**Comment by m50** [comment]
Just took a real quick look:

![image](https://user-images.githubusercontent.com/3577147/116819516-fbbcc180-ab35-11eb-9ff3-185c8216b4fd.png)

Seems to work for me?

**Comment by MathiasGilson** [comment]
Thank you for taking the time to have a look

autocomplete works for me too, but do you get anything in the console log ? like "focus" when you focus on the input ?

**Comment by m50** [comment]
So I figured out the issue. I noticed it was running it twice, and the problem was caused by your HTML file imporing the bundle.js file, while WebPack was injecting that itself as well, and I guess the React VM was having a conflict in the DOM, breaking the example.

**Comment by m50** [comment]
![image](https://user-images.githubusercontent.com/3577147/116831021-aa7ef300-ab72-11eb-93e6-0c64a0756640.png)


The changes I made (not worth a PR):

- remove the inclusion of bundle.js from the html file.
- `e.targe.event` => `e.target.value`

Then it worked!

**Comment by MathiasGilson** [comment]
![image](https://media.tenor.com/images/0283f8169ce766913c3bb8c615dd6ec7/tenor.gif)

**Comment by MathiasGilson** [comment]
thank @m50 your are the best!
