### ISSUE TITLE
Can't install `2.0` from NPM

### ISSUE THREAD

**Issue by riywo** [MathiasGilson/Tailwind-Styled-Component#11]
Failed example:

```
➜  npm i -D tailwind-styled-components@2.0.1
npm ERR! Cannot read property 'version' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riywo/.npm/_logs/2021-05-06T09_19_38_961Z-debug.log
```

No issue with `1.0.7`:
```
➜  npm i -D tailwind-styled-components@1.0.7

added 20 packages, and audited 764 packages in 3s

130 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Probably due to this unnecessary circular dependency:

https://github.com/MathiasGilson/Tailwind-Styled-Component/blob/4f7a7460ad4bfea5ff1cd4ab24792437c3ae838a/package.json#L52

This probably works up to `1.x` because `^1.0.5` accepts minor/patch versions: https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

However, it is hard to reproduce on local machine. Could you try to release a new version without this dependency?

My environment:

```
Darwin 20.4.0
node v14.15.1
npm  v7.5.2
```

**Comment by MathiasGilson** [comment]
Hello @riywo, 

thank you for reporting this issue!
I removed the circular dependency everything should be working now!

Please reopen if you have any issues

**Comment by riywo** [comment]
Thanks! `2.0.2` worked perfectly for me.
