### ISSUE TITLE
Extends demo in readme does not override background color

### ISSUE THREAD

**Issue by dfelber** [MathiasGilson/Tailwind-Styled-Component#12]
I tried to recreate the example from the readme where RedContainer should override the background color of DefaultContainer.

Instead of `bg-blue-600` getting replaced with `bg-red-300`, I get both classes in the result:

```html
<div class="bg-red-300 flex items-center bg-blue-600">
    <!-- children -->
</div>
```

Is there anything I am missing?
I am using version 2.0.2.

Thanks!

**Comment by MathiasGilson** [comment]
Hello!

Can you send me the code ?

Many thanks

**Comment by dfelber** [comment]
Sure: https://github.com/dfelber/Tailwind-Styled-Component-Issue-12
The code from the example is in https://github.com/dfelber/Tailwind-Styled-Component-Issue-12/blob/master/pages/index.js

**Comment by MathiasGilson** [comment]
Thank you for reporting this.
Unfortunately I checked and it's pretty hard to fully support overriding parent classes.
So I updated the readme to explain that this repo does not support it.
I would check https://github.com/ben-rogerson/twin.macro but I'm not entirely sure that they support it 

Please let me know if you find any way to implement it and I would be glad to try 😉
