### ISSUE TITLE
displayName

### ISSUE THREAD

**Issue by cj** [MathiasGilson/Tailwind-Styled-Component#13]
@MathiasGilson great lib!

One thing I think is missing is adding displayName like styled components does i.e. if its `tw.label` the displayName would be `tw.label` instead of Anonymous.

I can possibly create a pull request later this week!

**Comment by MathiasGilson** [comment]
Hey!
Yes that would be great, thank you 😁

**Comment by Olatade** [comment]
How do you select child elements ?? this does not work: 


const Container = tw.div`
  grid
  grid-cols-2
  bg-green-300

  .container-child {
    //....container child style
  }
`;

**Comment by MathiasGilson** [comment]
Hello @cj, 

displayName are now available in the new 2.1.0 version thanks to @Dudeonyx !
