### ISSUE TITLE
Tailwindcss plugins

### ISSUE THREAD

**Issue by rofazayn** [MathiasGilson/Tailwind-Styled-Component#17]
Hello,
Awesome work Mathias.

Is it possible to implement 3rd party plugins like tailwind-rtl to it?

Cheers

**Comment by MathiasGilson** [comment]
I'm not sure but technically it should work with tailwind plugins.
I've used it with https://github.com/tailwindlabs/tailwindcss-forms

Let me know if you have issue with a plugin
