### ISSUE TITLE
Does not work for something like framer-motion motion.div

### ISSUE THREAD

**Issue by gopherine** [MathiasGilson/Tailwind-Styled-Component#2]
From what i see is all the elements are hard-coded , I am not sure if that is by design or limited it would have been better to rather add support for custom element and generalize it, instead of having this attached to react only supported element

so right now <div> works but <motion.div> does not work I'm not sure if there is some work around this if there is i would like to use this and appreciate the help atleast from the overview i saw everything pretty much harcoded.

**Comment by MathiasGilson** [comment]
Hello,

Have you tried that ?
```ts
import tw from "tailwind-styled-components"
import { motion } from "framer-motion"

const AnimatedContainer = tw(motion.div)`
    flex
    items-center
    justify-center
`
```

**Comment by gopherine** [comment]
this is super clean , works really well :D 

```

const AnimatedContainer = tw.(motion.div)`
    flex
    items-center
    justify-center
`
```

i feel stupid i kept using dot there and thought it's not working. Thanks, also token of appreciation i really hope this project continue to be updated.his because i see other solutions are very complicated i.e. comparing to twin macro and styled-comp/emotion this is super clean and minified.

**Comment by MathiasGilson** [comment]
Thank you for your support 😉
