### ISSUE TITLE
nested css

### ISSUE THREAD

**Issue by dev-aly3n** [MathiasGilson/Tailwind-Styled-Component#20]
Hi devs
how we can write nested css like below:

tw.div`
flex

& h2 {
text-red-500
}
`

thank you for this awesome work Mathias

**Comment by MathiasGilson** [comment]
Hi @dev-aly3n, 

You can extend a Styled Component has shown on the the README.

### Extends Styled Component

Extend [styled components](https://github.com/styled-components/styled-components)

```js
const StyledComponentWithCustomCss = styled.div`
    filter: blur(1px);
`

const  = tw(StyledComponentWithCustomCss)`
   flex
`
```

*Css rule `filter` is not supported by default on TailwindCSS*
