### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by Olatade** [MathiasGilson/Tailwind-Styled-Component#21]
How do you select child elements ? This does not work:

const Container = tw.div`
grid
grid-cols-2
bg-green-300

.container-child {
//....container child style
}
`;

**Comment by MathiasGilson** [comment]
You can use a Styled Component to do that and then extend it

```js
const StyledContainer = styled.div`
    .container-child {
        //....container child style
    }
`

const Container = tw(StyledContainer)`
    grid
    grid-cols-2
    bg-green-300
`
```

**Comment by Olatade** [comment]
Hello!! thanks for your reply!. In your example above, container-child cannot contain tailwind styles. How do we achieve nesting by using only tailwind styles?

**Comment by MathiasGilson** [comment]
Nesting is a css thing so I don't think that you can nest css classes.
aka you can't do that 

```js
  .some-class {
        .nestest-class {
                // putting tailwind classes here doesn't make sense as it's supposed to be css props
               flex // as an example this won't work as it's not a valid css prop
         }
  }
```

You will have to create another children component or inject the css props directly
