### ISSUE TITLE
Function to combine tailwind classes to string

### ISSUE THREAD

**Issue by user753** [MathiasGilson/Tailwind-Styled-Component#22]
I would like to do something like this
```ts
const className = tw.cls`
  flex
  items-center
`
className === 'flex items-center'
```
Also, it could be usefull when props change many classes

```ts
const Title = tw.h1<TitleProps>`
  ${(p) => (p.$large ? tw.cls`
   flex
   items-center  
   h-10
   px-4
` : "text-base")}
  text-indigo-500
`
```

**Comment by AlexMason** [comment]
You don't really need to use a library to do that.  You can just write a function to do so.
`function cls(input) {
  return input[0].split("\n").join(' ').trim()
}

console.log(cls`
p-1
mt-2
mb-3
`);`

**Comment by MathiasGilson** [comment]
Hello @user753! 

@AlexMason has a good point, it's not really a function that requires a library but I could see some usecase where it could be pretty handy.

Making a PR should not be super difficult if you still think it's something you would need from this library 😉
