### ISSUE TITLE
Faulty Tailwind classRegex

### ISSUE THREAD

**Issue by Schwefelhexa** [MathiasGilson/Tailwind-Styled-Component#26]
When using the autocomplete settings provided in the README, the following happens:

![image](https://user-images.githubusercontent.com/40794797/127733173-50bfc7d6-5021-4489-b5dd-e82439535383.png)

The regex triggers after the second backtick.

**Comment by Schwefelhexa** [comment]
My apologies, looking back on it the issue is pretty hard to understand.
What happened is that I updated my VS Code settings according to the readme. However, that messed up the regex for the Tailwind plugin. Instead of correctly offering code completion between the two backticks, it only provided completion & highlighting after the second backtick, resulting in the screenshot above.

**Comment by MathiasGilson** [comment]
Hello @Schwefelhexa,

I understand the issue, unfortunately I was not able to reproduce it.
Which Tailwind plugin are you referring to?

Many thanks

**Comment by Schwefelhexa** [comment]
Hey @MathiasGilson,

Sorry for my late reply, I was talking about the official Tailwind plugin for VS Code.

The easiest way is to create a new project using Tailwind, and copy & paste the settings in the README into `.vscode/settings.json`.
Now, begin typing the following:
```javascript
const Container = tw.div``
```
You should notice what I have screenshotted above - autocomplete will only trigger after the second backtick.

**Comment by MathiasGilson** [comment]
@Schwefelhexa Oh I see the autocomplete works but also wrongly triggers after the second tick.
I though that it only started to work for you after the second tick and did not work properly between the two first ticks.

Great I've tested your fix and it seems to work, thank you so much for taking the time to explain and pushing this pull request!

Many thanks 😁

**Comment by Schwefelhexa** [comment]
No problem, I don't mind putting a little work into such a nice library!
