### ISSUE TITLE
Is it a way to override createGlobalStyle function of styledComponent

### ISSUE THREAD

**Issue by officefish** [MathiasGilson/Tailwind-Styled-Component#28]
Have a such global style:

```
import  {createGlobalStyle} from "styled-components"

/** Body setup */
export const GlobalStyle = createGlobalStyle`
  body {}
  `
```

Need to override it on:  
`<body class="min-h-screen bg-gray-100 text-sm" >
`

**Comment by officefish** [comment]
trying this way, it doesn't work:

```
/** Body setup */
export const GlobalStyle = createGlobalStyle`
  body {
    ${tw`min-h-screen bg-gray-100 text-sm`}
  }
  `
```

**Comment by MathiasGilson** [comment]
Hello @officefish, 

I'm not sure if it's the best use case for Tailwind Styled Components...

Please reopen if you still think that it's something the package should handle

Many thanks
