### ISSUE TITLE
Extend not working as expected.

### ISSUE THREAD

**Issue by joetifa2003** [MathiasGilson/Tailwind-Styled-Component#32]
When i extend a tw componnent the class names works fine but the dynamic ones don't work.

![image](https://user-images.githubusercontent.com/62658783/133008012-41d82570-8360-4ae4-b3e4-4b4dd3bc1a84.png)

Here in the "SpecialSection" componnent the pt-[72px] works fine but the $fullscreen $container don't work (even though the types gets extended)

**Comment by Dudeonyx** [comment]
That's because the transient props get filtered out in SpecialSection and does not get to Section.

**Comment by MathiasGilson** [comment]
This should work now thanks to @Dudeonyx PR!

Please update package to 2.1.0
