### ISSUE TITLE
Typo on Example

### ISSUE THREAD

**Issue by dtro-devuk** [MathiasGilson/Tailwind-Styled-Component#4]
Typo on README Example:

// Create a <SpecialBlueContainer> react component that renders a <section> with
// a special blue background color
const Container = styled.section`
  background-color: #0366d6;

SHOULD BE

const SpecialBlueContainer = styled.section

**Comment by MathiasGilson** [comment]
Fixed ! Thank you @dtro-devuk for reporting it 😉
