### ISSUE TITLE
v2.1.4 FATAL ERROR: Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by simonasdev** [MathiasGilson/Tailwind-Styled-Component#43]
Hello again. Thanks for the 2.1.2 version fix.

Unfortunately, upgrading to 2.1.4 and running `tsc` presented an error on a whole different level:
```
<--- Last few GCs --->

[2053:0x5bd9060]    88488 ms: Scavenge 2027.0 (2073.3) -> 2023.9 (2074.5) MB, 19.1 / 0.0 ms  (average mu = 0.355, current mu = 0.179) allocation failure 
[2053:0x5bd9060]    88515 ms: Scavenge 2028.2 (2074.5) -> 2025.9 (2077.8) MB, 11.2 / 0.0 ms  (average mu = 0.355, current mu = 0.179) allocation failure 
[2053:0x5bd9060]    88542 ms: Scavenge 2031.4 (2077.8) -> 2028.8 (2096.0) MB, 10.2 / 0.0 ms  (average mu = 0.355, current mu = 0.179) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00e10 node::Abort() [/usr/local/bin/node]
 2: 0xa1823b node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xcee09e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xcee417 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xea65d5  [/usr/local/bin/node]
 6: 0xeb5cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0xeb89ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0xe79b12 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0xe74[43](https://github.com/foroscom/foros-fe/runs/5145598143?check_suite_focus=true#step:5:43)c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/local/bin/node]
10: 0xe7[45](https://github.com/foroscom/foros-fe/runs/5145598143?check_suite_focus=true#step:5:45)15 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
11: 0x10dd41e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0x10dd4d3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/local/bin/node]
13: 0x11e9805 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x15e7cf9  [/usr/local/bin/node]
Aborted (core dumped)
error Command failed with exit code 134.
```
Not really sure where to begin debugging, since no other output is present. The JS itself works as expected, but `tsc` runs forever and then OOMs.
Do you have any idea what might have caused it?

**Comment by MathiasGilson** [comment]
maybe @Dudeonyx has an idea of where that issue comes from ?

**Comment by simonasdev** [comment]
well the `strict` was `true` for me to begin with. Seems like #44 could be suffering from the same culprit

**Comment by MathiasGilson** [comment]
yep, can you try rolling back to package version 2.1.2 ?

**Comment by simonasdev** [comment]
yeah, that is the last one that works for us, since 2.1.3 doesn't seem to be on npm

**Comment by MathiasGilson** [comment]
@Dudeonyx I think your typing is a bit excessive for tsc 😅
Can you try to remove some of the type checks?
I've tried on my own but I end up removing most of it maybe there is a cleaner solution?

I'll have to publish an updated version of the package with most of the typecheck removed so people's code compile.
Can you please have a look?

Many thanks 🙏

**Comment by MathiasGilson** [comment]
Okay 2.1.7 was published, I removed most of the nested typing, the tests pass immediatly without the heap limit allocation fail so that should address this issue for now.

**Comment by bcucumber** [comment]
Hi @MathiasGilson thanks a lot, the ts problem has been fixed! I have noticed however that typings for custom props have been lost and bring problems when using `no implicit any`. For example:

    const HelperText = tw.span<{ $error?: boolean }>`
      ${({ $error }) =>
        clsx({
          'text-text-500': !$error,
          'text-danger-500': $error,
        })}
    `;

throws `TS7031: Binding element '$error' implicitly has an 'any' type.`

Thanks!

**Comment by mauriceackel** [comment]
@MathiasGilson It would be lovely if we could get a fix of the typing issue without the types being removed all together ❤️

**Comment by rayzr522** [comment]
any update on this? 100% happy to help out myself, I'm pretty experienced with TypeScript's typing system and doing weird wonky metaprogramming with it. do you know what part of the typings are actually the culprit for the performance issues? that would be a helpful starting point, otherwise happy to profile and debug this myself -- I really want to use this library but still be able to get typings!

**Comment by MathiasGilson** [comment]
Hello @rayzr522! I would love to get some help on that as I'm not the best when in comes to nested typing on typescript.

You can see on this [commit](https://github.com/MathiasGilson/Tailwind-Styled-Component/commit/5ea6caaa56c598d45eb01bb69c33f58f707f926c) that I removed a lot of typing for the tests to pass.

I'm afraid that I didn't understand which one was failing exactly but I tried to removed as few as possible with trial and errors.

Would appreciate if you would find some time to give it a look 😉
