### ISSUE TITLE
Feature: Expose css-like utility function known from styled-components

### ISSUE THREAD

**Issue by johnolos** [MathiasGilson/Tailwind-Styled-Component#46]
First of all, trying this library, and loving it so far! 👏 

I was trying to structure my code and attempting to create shared styling between components that fundamentally do not share same functionally.

To my knowledge; one could do this with styled components:

```typescript
import { css } from 'styled-components';

const outlineStyle = css`
  outline-width: 2px;
  outline-style: 'solid';
  outline-color: 'orange';
`
// Button.tsx

const Button = styled.button`
  ${outlineStyle}
`

const Input = styled.input`
  ${outlineStyle}
`
```

Basically, I think a wrapper `css`-function exported from your library would be a great addition that is aware of tailwind-expressions.

**Comment by kla-trackunit** [comment]
I have run into a similar thing, the best i could come up with was the solution posted in this comment:
https://github.com/MathiasGilson/Tailwind-Styled-Component/issues/45#issuecomment-1047488359

**Comment by MathiasGilson** [comment]
Extending a parent component containing the classes wouldn't work?

```tsx
const DefaultContainer = tw.div`
    flex
    items-center
`
const RedContainer = tw(DefaultContainer)`
    bg-red-300
`
```

**Comment by johnolos** [comment]
That does the trick in a small fashion. I suspect in a larger code-base you might want other ways to express yourself.

Closing the issue for now.

**Comment by MathiasGilson** [comment]
Please re-open if you find a use case that you think would justify such a utility!
Otherwise PR are always welcomed 😉

**Comment by jdtzmn** [comment]
I'd like to reopen this issue. @MathiasGilson the code included above does not satisfy the use case in which `DefaultContainer` and `RedContainer` are built on differing underlying elements.

In my case, I'd like to style a `textarea` and an `input` the same way without repeating the style template string.
