### ISSUE TITLE
Feature: using tailwind-merge library to override parent classes

### ISSUE THREAD

**Issue by bcucumber** [MathiasGilson/Tailwind-Styled-Component#48]
Hi! First of all, this is a great library as it makes working with Tailwind a lot easier, and I'm very thankful for that. 

Like the documentation explains, this library doesn't override parent classes, it just concatenates the different classes and the result will depend on each case. Which brings to the following suggestion: how possible would it be to switch the use of the current library `tailwindcss-classnames` to `tailwind-merge` (https://github.com/dcastil/tailwind-merge) as this other library already handles tailwind classes overriding?

I understand that this might be a breaking change given the current state of the library (if it's a hard change, but maybe it could be configurable?). However I believe users would benefit a lot more if it were possible to override parent classes.

Thanks!

**Comment by MathiasGilson** [comment]
Great idea! I'll have a look, PR are welcome if you have time 😉

**Comment by bcucumber** [comment]
Hi @MathiasGilson, I submitted a PR with the changes for this feature. Feel free to check it out and run the checks on your end whenever you can!

**Comment by MathiasGilson** [comment]
Will do! Thank you so much for taking the time to do it 😉

**Comment by MathiasGilson** [comment]
Implemented in the last version 2.1.6!

Thank you for your PR!
