### ISSUE TITLE
Tailwind Intellisense bug

### ISSUE THREAD

**Issue by idChef** [MathiasGilson/Tailwind-Styled-Component#49]
When using Tailwind Intellisense fix from the readme, writing `flex` results in this autocomplete behaviour:

![image](https://user-images.githubusercontent.com/34141636/159368928-a2d62abc-490f-4638-b6c2-86e01a42d362.png)

**Comment by MathiasGilson** [comment]
Hello @idChef, 

Please check you VSCode intellisense config for any conflics.
I was unable to reproduce this issue, closing for now
