### ISSUE TITLE
Any way to get intelliSense to work with this package?

### ISSUE THREAD

**Issue by mhedengren** [MathiasGilson/Tailwind-Styled-Component#5]
Love the idea of this package, is there any way to get the vscode intellisense feature to work along with this?

**Comment by frederik-oestergaard** [comment]
VS Code autocompetion for StyledComponents comes from the extension **typescript-styled-plugin**. 
Luckily this extension can be configured to provide autocompletion for other tags, see link below.
[typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin#configuration). 

I fixed this by adding following in our `tsconfig.json` file:
```
...
 "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "styled",
          "css",
          "sty",
          "tw"
        ]
      }
   ]
...
```

**Comment by sethstha** [comment]
You can get that from tailwindcss-intelisense for vscode. Just pass the regex. This should do it


```
"scss.validate": false,
"editor.quickSuggestions": {
    "strings": true
},
"editor.autoClosingQuotes": "always",
"tailwindCSS.experimental.classRegex": [
    "tw`([^`]*)", // tw`...`
    "tw=\"([^\"]*)", // <div tw="..." />
    "tw={\"([^\"}]*)", // <div tw={"..."} />
    "tw\\.\\w+`([^`]*)", // tw.xxx`...`
    "tw\\(.*?\\)`([^`]*)" // tw(Component)`...`
],
"tailwindCSS.includeLanguages": {
  "typescript": "javascript",
  "typescriptreact": "javascript"
}
```

**Comment by MathiasGilson** [comment]
Thank you @sethstha ! I will add that to the readme.
