### ISSUE TITLE
import Image from 'next/image' - how to tsc its tailwind css?

### ISSUE THREAD

**Issue by Mic1** [MathiasGilson/Tailwind-Styled-Component#50]
`import Image from 'next/image'`

`<Image
            className="absolute inset-0 h-full w-full rounded-lg bg-gray-400 object-cover shadow-md"
            etc
          />`

How do I tsc this> Thanks.

Tried moving into the enclosing div but not at all the same thing   . am reading that Next changed the way Image behaves in the latest version that has broken a lot of people's code. One suggestion is to move the css into the enclosing div but has to be "relative". Tried this but image looks distorted.

**Comment by idChef** [comment]
Try the `layout` prop on the `Image` tag. The way you work with the `next/image` is the same as you would normally.

**Comment by MathiasGilson** [comment]
I don't see how this is related to Tailwind Styled Components, closing for now, please add a way to reproduce if you think this is something that this library should solve.

**Comment by Mic1** [comment]
Yes please do - I was asking for help in using tsc with next/img, not suggesting that there was a problem with tsc ... apologies if this was the wrong place to connect with you.

    On Thursday, April 14, 2022, 05:11:52 PM MDT, Mathias Gilson ***@***.***> wrote:  
 
 


Closed #50.
