### ISSUE TITLE
Using props does not work 

### ISSUE THREAD

**Issue by azzlack** [MathiasGilson/Tailwind-Styled-Component#52]
Given the following code

```ts
const TimelineCurrent = tw.div<{ position: number }>`
  absolute
  left-0
  top-[0.575rem]
  ${(p) => `w-[calc(${p.position}%-0.75rem)]`}
  h-[0.35rem]
`;
```

it renders the following HTML

```html
<div position="100" class="absolute left-0 top-[0.575rem] w-[calc(100%-0.75rem)] h-[0.35rem]"></div>
```

But the `w-[calc(100%-0.75rem)]` part is not picked up by Tailwind JIT, so it has no effect. Am I doing something wrong here?

**Comment by MathiasGilson** [comment]
Yeah I'm not sure that you can use custom JIT classes with props...

**Comment by mauriceackel** [comment]
JIT runs at build time, but your class name gets computed at runtime.. Hence, tailwind does not know the actual name of the class at runtime and cannot generate the CSS for it.

**Comment by azzlack** [comment]
Thanks for the response. Is there any way to do what I am trying to accomplish without using style attributes then?

**Comment by MathiasGilson** [comment]
You can use a styled component and extend it to add the tailwind classes. You should be able to set the width with props at runtime using basic css in the styled component

**Comment by alexjidras** [comment]
@azzlack that's not an issue. You wrote the calc css syntax wrong. `calc(100%-0.75rem)` will not work even with css. You should add a space around the `-` operator. Like this `calc(100% - 0.75rem)`. With tailwind custom classes spaces inside it should be marked with `_` so your final class should be `w-[calc(100%_-_0.75rem)]`.
