### ISSUE TITLE
Will this work with purge css?

### ISSUE THREAD

**Issue by vedantroy** [MathiasGilson/Tailwind-Styled-Component#57]
I know tailwind css detects whether a class is used based on `className`. Since components defined using this format are not using `className`, will the resulting css file still include the correct class names?

**Comment by randallmlough** [comment]
Yes. Tailwind's purge mechanism reads the whole file not just what is defined in `<div className='some-class'>` for example

**Comment by vedantroy** [comment]
Oh that's quite nice, are there docs on how this works?
