### ISSUE TITLE
Add CSS to tailwind styled component

### ISSUE THREAD

**Issue by AidanRRR** [MathiasGilson/Tailwind-Styled-Component#68]
Is it possible to add CSS to a tailwind styled componet (not extend)? Combining both CSS and tailwind classes would be nice!

**Comment by MathiasGilson** [comment]
No because tailwind properties are actually CSS classes and CSS pure css would be CSS properties which are not compatible

**Comment by AidanRRR** [comment]
Thanks for following up!

Yes, but sometimes not everything is do-able with tailwind and doing it with an extend takes a bit of the 'cleanliness' away in my part as you have a few extra lines and not have sort of a quick view of the actual generated css.
