### ISSUE TITLE
Enhancement: export twMerge

### ISSUE THREAD

**Issue by alexjidras** [MathiasGilson/Tailwind-Styled-Component#69]
you could export twMerge function from 'tailwind-merge' as part of this package. So we don't have to install 'tailwind-merge' as a separate package when tailwind-styled-components already comes with it.

Thoughts on syntax:
```js
import tw, { twMerge } from 'tailwind-styled-components';
```

or
```js
import tw from 'tailwind-styled-components';

// usage:

tw.merge('pl-4', undefined, false, props.className)
```

**Comment by rubens-lopes** [comment]
My humble opinion:

I don't see everybody that uses `tailwind-styled-components` with a mandatory need of `tailwind-merge`, so if it is a special case it should be add as dependency when need only.

Libraries should be a black box, in case the author needs to chance the internal implementation it would broken whoever is using that internal dependency.

**Comment by alexjidras** [comment]
@rubens-lopes Good argument. Thanks
